apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: j5xuhxea4-go 
  janus-idp.io/tekton: j5xuhxea4-go
  backstage.io/kubernetes-id: j5xuhxea4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j5xuhxea4-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml